### ISSUE TITLE
on variables sharing

### ISSUE THREAD

**Issue by thien-do** [axieinfinity/festival#8]
Don't use @apply. They are unnecessarily complicated and can be solved easier with native solution: CSS variables. For example:

```css
:root {
  --color-red: #123456
}
```

to use in tailwinds:
```jsx
red: "var(--color-red)",
```

to use outside of tailwind:
```css
body {
  color: var(--color-red);
}
```
